[package]
name = "pyrsia_cli"
authors = ["Mitali Bisht <mitalib@jfrog.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "3.0.0-beta.5", features = ["yaml"] }
futures = { version = "0.3.*"}
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = [ "full"] }
walkdir = "2.3.2"

pyrsia_node = { path = "../pyrsia_node" }


[[bin]]
name = "pyrsia"
path = "src/main.rs"

[dev-dependencies]
expectest = "0.10.0"
